### ISSUE TITLE
NREL SPA not included? Python error `No module named '_spa`

### ISSUE THREAD

**Issue by Polyrhythm** [spectralskylight/skydataviewer#1]
Upon running `spectralskyviewer.py` with Python 3.8, following readme instructions.

```
...\spectralskyviewer>python spectralskyviewer.py
Traceback (most recent call last):
  File "...\spectralskyviewer\spa\spa.py", line 23, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spa._spa'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spectralskyviewer.py", line 22, in <module>
    import utility_data
  File "...\spectralskyviewer\utility_data.py", line 16, in <module>
    import spa
  File "...\spectralskyviewer\spa\__init__.py", line 10, in <module>
    from .spa import *
  File "...\spectralskyviewer\spa\spa.py", line 26, in <module>
    _spa = swig_import_helper()
  File "...\spectralskyviewer\spa\spa.py", line 25, in swig_import_helper
    return importlib.import_module('_spa')
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_spa'
```

**Comment by delrocco** [comment]
I'm so sorry for the delay on this! I wasn't getting the notifications. すみません, 私を許してください!

I wrapped the [NREL SPA .c code](https://midcdmz.nrel.gov/spa/) with SWIG to produce a Python module. That should have been included, but perhaps your Python path couldn't find it for some reason.

I will look at this as soon as I can.

**Comment by tmwitczak** [comment]
I encountered exactly the same issue today and the solution was to **go to the _spa/build/vs2017_dll_ folder and run the build** which produces the missing *_spa.pyd* file. The _include_ and _lib_ paths in the project file have a hard-coded Python path, though, so these may need changing beforehand.

**Comment by clearskyperson** [comment]
Hi all ! 
Same problem for me today when executing spectralskyviewer.py : No module named '_spa'
I couldn't get to grips with @tmwitczak solution either. 
Would you have an idea for a solution @delrocco ? :)
